name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Validate update.json
        run: ./gradlew checkUpdateJson --no-daemon --stacktrace

      - name: Build (skip tests)
        run: ./gradlew build -x test --no-daemon --stacktrace

